import './globals.css'
import './layout.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head/>
      <body>
        <nav className="navbar">
          <div className="logo"></div>
          <div className="wrapper">
            <ul>
              <li>
                <a href="#">About</a>
              </li>
              <li>
                <a href="#">Work</a>
              </li>
            </ul>
          </div>  
        </nav>
        {children}
      </body>
    </html>
  )
}
